export const FETCH_PETS_REQUEST = 'FETCH_PETS_REQUEST';
export const FETCH_PETS_SUCCESS = 'FETCH_PETS_SUCCESS';
export const FETCH_PETS_ERROR = 'FETCH_PETS_ERROR';

export const SELECT_ALL_PETS = 'SELECT_ALL_PETS';
export const DESELECT_ALL_PETS = 'DESELECT_ALL_PETS';
export const SELECT_PET = 'SELECT_PET';